#!/bin/bash
# =============================================================================
# Setup Instruqt Environment
# =============================================================================
# Extracts environment variables from Instruqt and creates infra/.env
# Run this on host-1 in the Instruqt environment
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="${REPO_DIR}/infra/.env"

echo "==============================================================="
echo "  SETUP INSTRUQT ENVIRONMENT"
echo "==============================================================="
echo ""

# Check if we're in Instruqt
if [[ -z "${INSTRUQT_PARTICIPANT_ID:-}" ]]; then
    echo "[WARN] INSTRUQT_PARTICIPANT_ID not set - may not be in Instruqt environment"
fi

# Extract values from environment (with defaults)
ELASTIC_ENDPOINT="${ELASTICSEARCH_URL:-http://kubernetes-vm:30920}"
ELASTIC_API_KEY="${ELASTICSEARCH_APIKEY:-}"
KIBANA="${KIBANA_URL:-http://kubernetes-vm:30002}"
APM_ENDPOINT="${ELASTIC_APM_SERVER_ENDPOINT:-http://kubernetes-vm:8200}"
APM_SECRET="${ELASTIC_APM_SERVER_SECRET:-}"

# Validate required variables
if [[ -z "$ELASTIC_API_KEY" ]]; then
    echo "[ERROR] ELASTICSEARCH_APIKEY not found in environment"
    echo "        Please ensure Instruqt has provisioned the API key"
    exit 1
fi

echo "[INFO] Detected environment variables:"
echo "       ELASTIC_ENDPOINT: ${ELASTIC_ENDPOINT}"
echo "       KIBANA_URL: ${KIBANA}"
echo "       APM_ENDPOINT: ${APM_ENDPOINT}"
echo "       API_KEY: ${ELASTIC_API_KEY:0:20}..."
echo ""

# Create .env file
cat > "${ENV_FILE}" << EOF
# =============================================================================
# From Commit to Culprit - Instruqt Environment Configuration
# =============================================================================
# Auto-generated by setup-instruqt-env.sh
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# =============================================================================

# -----------------------------------------------------------------------------
# Environment Detection
# -----------------------------------------------------------------------------
ENVIRONMENT=instruqt

# -----------------------------------------------------------------------------
# Elastic Connection (from Instruqt environment)
# -----------------------------------------------------------------------------
ELASTIC_ENDPOINT=${ELASTIC_ENDPOINT}
ELASTIC_API_KEY=${ELASTIC_API_KEY}
KIBANA_URL=${KIBANA}

# -----------------------------------------------------------------------------
# OpenTelemetry / APM Configuration
# -----------------------------------------------------------------------------
OTEL_EXPORTER_OTLP_ENDPOINT=${APM_ENDPOINT}
OTEL_EXPORTER_OTLP_AUTH="Bearer ${APM_SECRET}"
OTEL_EXPORTER_OTLP_INSECURE=true

# APM Secret Token (for reference)
ELASTIC_APM_SECRET_TOKEN=${APM_SECRET}

# -----------------------------------------------------------------------------
# Webhook URL (for automated rollback)
# -----------------------------------------------------------------------------
# host-1 is reachable from kubernetes-vm via hostname
WEBHOOK_PUBLIC_URL=http://host-1:9000

# -----------------------------------------------------------------------------
# Container Registry
# -----------------------------------------------------------------------------
REGISTRY=localhost:5000

# -----------------------------------------------------------------------------
# Service Versions
# -----------------------------------------------------------------------------
ORDER_SERVICE_VERSION=v1.0
INVENTORY_SERVICE_VERSION=v1.0
PAYMENT_SERVICE_VERSION=v1.0

# -----------------------------------------------------------------------------
# Business Constants
# -----------------------------------------------------------------------------
AVERAGE_ORDER_VALUE=47.50
EOF

echo "[SUCCESS] Created ${ENV_FILE}"
echo ""

# Verify connectivity (with 5 second timeout)
echo "[INFO] Verifying Elasticsearch connectivity..."
ES_STATUS=$(curl -s --max-time 5 -o /dev/null -w "%{http_code}" \
    -H "Authorization: ApiKey ${ELASTIC_API_KEY}" \
    "${ELASTIC_ENDPOINT}/_cluster/health" 2>/dev/null || echo "000")
if [[ "$ES_STATUS" == "200" ]]; then
    echo "[SUCCESS] Elasticsearch connection verified"
else
    echo "[WARN] Could not verify Elasticsearch connection (HTTP ${ES_STATUS})"
    echo "       This may be normal if kubernetes-vm is still starting"
fi

echo ""
echo "[INFO] Verifying APM Server connectivity..."
APM_STATUS=$(curl -s --max-time 5 -o /dev/null -w "%{http_code}" \
    "${APM_ENDPOINT}/" 2>/dev/null || echo "000")
if [[ "$APM_STATUS" =~ ^(200|403)$ ]]; then
    echo "[SUCCESS] APM Server reachable"
else
    echo "[WARN] Could not verify APM Server connection (HTTP ${APM_STATUS})"
fi

echo ""
echo "==============================================================="
echo "  SETUP COMPLETE"
echo "==============================================================="
echo ""
echo "Next steps:"
echo "  1. Start registry:     cd infra && docker compose up -d registry"
echo "  2. Build images:       ./scripts/build-images.sh"
echo "  3. Start services:     cd infra && docker compose up -d"
echo "  4. Provision Elastic:  ./scripts/setup-elastic.sh"
echo "  5. Generate traffic:   ./scripts/load-generator.sh &"
echo ""
